export const ICECREAM_LOAD_START = 'ICECREAM_LOAD_START';
export const ICECREAM_LOAD_SUCCESS = 'ICECREAM_LOAD_SUCCESS';
export const ICECREAM_LOAD_FAIL = 'ICECREAM_LOAD_FAIL';

export const ICECREAM_ADD_START = 'ICECREAM_ADD_START';
export const ICECREAM_ADD_SUCCESS = 'ICECREAM_ADD_SUCCESS';
export const ICECREAM_ADD_FAIL = 'ICECREAM_ADD_FAIL';
